name: 'Renew github app access token composite action'

inputs:
  ROOT_KV_NAME:
    description: ''
    required: true
  GITHUB_PAT:
    description: ''
    required: true
  resource_group_name:
    description: 'name of the resource group to create resources in'
    required: true
  CICD_GHAPP_RUNNER_GROUP_ID:
    description: ''
    required: true
  CICD_GHAPP_RUNNER_GROUP_KEY:
    description: ''
    required: true

runs:
  using: 'composite'
  steps:

    - name: Generate token for GitHub App
      id: generate-token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ inputs.CICD_GHAPP_RUNNER_GROUP_ID }}
        private_key: ${{ inputs.CICD_GHAPP_RUNNER_GROUP_KEY }}

    - name: Add Github App Generate Token in KV
      shell: pwsh
      run: |
        az keyvault secret set --name ${{ inputs.GITHUB_PAT }} --vault-name ${{ inputs.ROOT_KV_NAME }} --value ${{ steps.generate-token.outputs.token }}
