#variables values in int env
AZ_RESOURCE_GROUP_NAME = "rg-int-xtech"
ENVIRONMENT = "i"
KV_NAME = "kv-int-xtech"
APP_INSIGHTS_NAME = "appins-int-xtech"
ENVIRONMENT_NAME = "Integration"
ENV_OWNER_GROUP_NAME = "AZR-XTECH-INT-Owner"
ENV_CONTRIBUTOR_GROUP_NAME = "AZR-XTECH-INT-Contributor"
SP_BACKEND_NAME = "sp-int-xtech"
SP_ENV = "AZR-XTECH-Builder-Integration"
