#variables values in qual env
AZ_RESOURCE_GROUP_NAME = "rg-qual-xtech"
ENVIRONMENT = "q"
KV_NAME = "kv-qual-xtech"
APP_INSIGHTS_NAME = "appins-qual-xtech"
ENVIRONMENT_NAME = "Qualification"
ENV_OWNER_GROUP_NAME = "AZR-XTECH-QUAL-Owner"
ENV_CONTRIBUTOR_GROUP_NAME = "AZR-XTECH-QUAL-Contributor"
SP_BACKEND_NAME = "sp-qual-xtech"
SP_ENV_QUAL = "AZR-XTECH-Builder-Qualification"
CONTAINER_REGISTRY_NAME = "acr-qual-xtech"
PSQL_NAME = "psql-q-xtech"
FRONTEND_DNS_RECORD_NAME = "mypaper-qa"
